name: depurador
description: "Aplicación para depuración de código usando inteligencia artificial"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.1.1
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  flutter_markdown: ^0.6.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env

# Configuración de flutter_launcher_icons (DEBE ESTAR FUERA de la sección flutter)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"